INSERT INTO Team (teamCode, teamName, teamCountryCode) VALUES
  ('ENG001', 'Fulham', 'ENG'),
  ('ENG002', 'Burnley F.C.', 'ENG'),
  ('ENG003', 'A.F.C. Bournemouth', 'ENG'),
  ('ENG004', 'Newcastle United', 'ENG'),
  ('ENG005', 'Sheffield Wednesday', 'ENG'),
  ('ENG006', 'Queens Park Rangers', 'ENG'),
  ('ENG007', 'Norwich City', 'ENG'),
  ('ENG008', 'Brighton & Hove Albion', 'ENG'),
  ('ENG009', 'Birmingham City', 'ENG'),
  ('ENG010', 'Tottenham Hotspur F.C.', 'ENG'),
  ('ENG011', 'Nottingham Forest', 'ENG'),
  ('ENG012', 'West Ham United F.C.', 'ENG'),
  ('ENG013', 'Manchester United F.C.', 'ENG'),
  ('ENG014', 'Middlesbrough F.C.', 'ENG'),
  ('ENG015', 'Bristol City', 'ENG'),
  ('ENG016', 'Huddersfield Town', 'ENG'),
  ('ENG017', 'Stoke City F.C.', 'ENG'),
  ('ENG018', 'Arsenal F.C.', 'ENG'),
  ('ENG019', 'Hull City A.F.C.', 'ENG'),
  ('ENG020', 'West Bromwich Albion F.C.', 'ENG'),
  ('ENG021', 'Wolverhampton Wanderers', 'ENG'),
  ('ENG022', 'Ipswich Town', 'ENG'),
  ('ENG023', 'Aston Villa', 'ENG'),
  ('ENG024', 'Burton Albion', 'ENG'),
  ('ENG025', 'Sunderland A.F.C.', 'ENG'),
  ('ENG026', 'Derby County', 'ENG'),
  ('ENG027', 'Everton F.C.', 'ENG'),
  ('ENG028', 'Liverpool F.C.', 'ENG'),
  ('ENG029', 'Watford F.C.', 'ENG'),
  ('ENG030', 'Wigan Athletic', 'ENG'),
  ('ENG031', 'Leeds United', 'ENG'),
  ('ENG032', 'Southampton F.C.', 'ENG'),
  ('ENG033', 'Preston North End', 'ENG'),
  ('ENG034', 'Brentford', 'ENG'),
  ('ENG035', 'Leicester City F.C.', 'ENG'),
  ('ENG036', 'Reading', 'ENG'),
  ('ENG037', 'Crystal Palace F.C.', 'ENG'),
  ('ENG038', 'Chelsea F.C.', 'ENG'),
  ('ENG039', 'Rotherham United', 'ENG'),
  ('ENG040', 'Manchester City F.C.', 'ENG'),
  ('ENG041', 'Barnsley', 'ENG'),
  ('ENG042', 'Blackburn Rovers', 'ENG'),
  ('ENG043', 'Bolton', 'ENG');
