INSERT INTO Team (teamCode, teamName, teamCountryCode) VALUES
  ('ESP001', 'Cadiz', 'ESP'),
  ('ESP002', 'Sevilla Atletico', 'ESP'),
  ('ESP003', 'Huesca', 'ESP'),
  ('ESP004', 'Levante', 'ESP'),
  ('ESP005', 'Gimnastic', 'ESP'),
  ('ESP006', 'Elche', 'ESP'),
  ('ESP007', 'Getafe', 'ESP'),
  ('ESP008', 'Leganes', 'ESP'),
  ('ESP009', 'Granada', 'ESP'),
  ('ESP010', 'Cordoba', 'ESP'),
  ('ESP011', 'Alcorcon', 'ESP'),
  ('ESP012', 'Tenerife', 'ESP'),
  ('ESP013', 'Oviedo', 'ESP'),
  ('ESP014', 'Las Palmas', 'ESP'),
  ('ESP015', 'Valladolid', 'ESP'),
  ('ESP016', 'Girona', 'ESP'),
  ('ESP017', 'Numancia', 'ESP'),
  ('ESP018', 'Real Madrid', 'ESP'),
  ('ESP019', 'Murcia', 'ESP'),
  ('ESP020', 'Real Betis', 'ESP'),
  ('ESP021', 'Mallorca', 'ESP'),
  ('ESP022', 'Celta', 'ESP'),
  ('ESP023', 'Alaves', 'ESP'),
  ('ESP024', 'Espanyol', 'ESP'),
  ('ESP025', 'Deportivo', 'ESP'),
  ('ESP026', 'Osasuna', 'ESP'),
  ('ESP027', 'FC Barcelona', 'ESP'),
  ('ESP028', 'Rayo Vallecano', 'ESP'),
  ('ESP029', 'Reus Deportiu', 'ESP'),
  ('ESP030', 'Sporting Gijon', 'ESP'),
  ('ESP031', 'Mirandes', 'ESP'),
  ('ESP032', 'Eibar', 'ESP'),
  ('ESP033', 'Sevilla FC', 'ESP'),
  ('ESP034', 'Almeria', 'ESP'),
  ('ESP035', 'Zaragoza', 'ESP'),
  ('ESP036', 'Lugo', 'ESP'),
  ('ESP037', 'Athletic', 'ESP'),
  ('ESP038', 'Malaga CF', 'ESP'),
  ('ESP039', 'Atletico Madrid', 'ESP'),
  ('ESP040', 'Real Sociedad', 'ESP'),
  ('ESP041', 'Villarreal', 'ESP'),
  ('ESP042', 'Valencia', 'ESP'),
  ('ESP043', 'Racing', 'ESP');
