INSERT INTO Team (teamCode, teamName, teamCountryCode) VALUES
  ('ITA001', 'Pisa', 'ITA'),
  ('ITA002', 'Modena', 'ITA'),
  ('ITA003', 'Pistoiese', 'ITA'),
  ('ITA004', 'Como', 'ITA'),
  ('ITA005', 'Padova', 'ITA'),
  ('ITA006', 'Novara', 'ITA'),
  ('ITA007', 'Genoa', 'ITA'),
  ('ITA008', 'Arezzo', 'ITA'),
  ('ITA009', 'Melfi', 'ITA'),
  ('ITA010', 'Cesena', 'ITA'),
  ('ITA011', 'Virtus Francavilla', 'ITA'),
  ('ITA012', 'Reggiana', 'ITA'),
  ('ITA013', 'Crotone', 'ITA'),
  ('ITA014', 'Salernitana', 'ITA'),
  ('ITA015', 'Benevento', 'ITA'),
  ('ITA016', 'Milan', 'ITA'),
  ('ITA017', 'Lazio', 'ITA'),
  ('ITA018', 'Vibonese', 'ITA'),
  ('ITA019', 'Teramo', 'ITA'),
  ('ITA020', 'Viterbese', 'ITA'),
  ('ITA021', 'Atalanta', 'ITA'),
  ('ITA022', 'Akragas', 'ITA'),
  ('ITA023', 'Parma', 'ITA'),
  ('ITA024', 'Bologna', 'ITA'),
  ('ITA025', 'Sudtirol', 'ITA'),
  ('ITA026', 'Fidelis Andria', 'ITA'),
  ('ITA027', 'Juventus', 'ITA'),
  ('ITA028', 'Ascoli', 'ITA'),
  ('ITA029', 'Olbia', 'ITA'),
  ('ITA030', 'Cosenza', 'ITA'),
  ('ITA031', 'Frosinone', 'ITA'),
  ('ITA032', 'Siena', 'ITA'),
  ('ITA033', 'Venezia', 'ITA'),
  ('ITA034', 'Forli', 'ITA'),
  ('ITA035', 'AlbinoLeffe', 'ITA'),
  ('ITA036', 'Perugia', 'ITA'),
  ('ITA037', 'SPAL', 'ITA'),
  ('ITA038', 'Carpi', 'ITA'),
  ('ITA039', 'Avellino', 'ITA'),
  ('ITA040', 'Santarcangelo', 'ITA'),
  ('ITA041', 'Brescia', 'ITA'),
  ('ITA042', 'Cremonese', 'ITA'),
  ('ITA043', 'Empoli', 'ITA'),
  ('ITA044', 'Spezia', 'ITA'),
  ('ITA045', 'Ternana', 'ITA'),
  ('ITA046', 'Fiorentina', 'ITA'),
  ('ITA047', 'Verona', 'ITA'),
  ('ITA048', 'Reggina', 'ITA'),
  ('ITA049', 'Casertana', 'ITA'),
  ('ITA050', 'Renate', 'ITA'),
  ('ITA051', 'Pro Piacenza', 'ITA'),
  ('ITA052', 'Juve Stabia', 'ITA'),
  ('ITA053', 'Palermo', 'ITA'),
  ('ITA054', 'Lecce', 'ITA'),
  ('ITA055', 'Roma', 'ITA'),
  ('ITA056', 'Siracusa', 'ITA'),
  ('ITA057', 'Paganese', 'ITA'),
  ('ITA058', 'Racing Roma', 'ITA'),
  ('ITA059', 'Cagliari', 'ITA'),
  ('ITA060', 'Prato', 'ITA'),
  ('ITA061', 'Vicenza', 'ITA'),
  ('ITA062', 'Napoli', 'ITA'),
  ('ITA063', 'Mantova', 'ITA'),
  ('ITA064', 'Sambenedettese', 'ITA'),
  ('ITA065', 'Monopoli', 'ITA'),
  ('ITA066', 'Bassano Virtus', 'ITA'),
  ('ITA067', 'Pro Vercelli', 'ITA'),
  ('ITA068', 'Gubbio', 'ITA'),
  ('ITA069', 'FeralpiSalo', 'ITA'),
  ('ITA070', 'Lumezzane', 'ITA'),
  ('ITA071', 'Latina', 'ITA'),
  ('ITA072', 'Pescara', 'ITA'),
  ('ITA073', 'Bari', 'ITA'),
  ('ITA074', 'Alessandria', 'ITA'),
  ('ITA075', 'Ancona', 'ITA'),
  ('ITA076', 'Maceratese', 'ITA'),
  ('ITA077', 'Lupa Roma', 'ITA'),
  ('ITA078', 'Cittadella', 'ITA'),
  ('ITA079', 'Internazionale', 'ITA'),
  ('ITA080', 'Catanzaro', 'ITA'),
  ('ITA081', 'Foggia', 'ITA'),
  ('ITA082', 'Pordenone', 'ITA'),
  ('ITA083', 'Livorno', 'ITA'),
  ('ITA084', 'Fondi', 'ITA'),
  ('ITA085', 'Chievo', 'ITA'),
  ('ITA086', 'Matera', 'ITA'),
  ('ITA087', 'Messina', 'ITA'),
  ('ITA088', 'Taranto', 'ITA'),
  ('ITA089', 'Catania', 'ITA'),
  ('ITA090', 'Sassuolo', 'ITA'),
  ('ITA091', 'Trapani', 'ITA'),
  ('ITA092', 'Udinese', 'ITA'),
  ('ITA093', 'Sampdoria', 'ITA'),
  ('ITA094', 'Pontedera', 'ITA'),
  ('ITA095', 'Giana Erminio', 'ITA'),
  ('ITA096', 'Torino', 'ITA'),
  ('ITA097', 'Tuttocuoio', 'ITA'),
  ('ITA098', 'Fano', 'ITA'),
  ('ITA099', 'Carrarese', 'ITA'),
  ('ITA100', 'Lucchese', 'ITA'),
  ('ITA101', 'Piacenza', 'ITA'),
  ('ITA102', 'Virtus Entella', 'ITA');
