INSERT INTO Team (teamCode, teamName, teamCountryCode) VALUES
  ('DEU001', 'VfB Einheit zu Pankow', 'DEU'),
  ('DEU002', 'SV Röchling Völklingen', 'DEU'),
  ('DEU003', 'Arminia Hannover', 'DEU'),
  ('DEU004', 'BFC Viktoria 1889', 'DEU'),
  ('DEU005', 'ASV Neumarkt', 'DEU'),
  ('DEU006', 'SV Dessau 05', 'DEU'),
  ('DEU007', 'TSV Landsberg', 'DEU'),
  ('DEU008', 'Würzburger FV', 'DEU'),
  ('DEU009', 'VfB Lübeck', 'DEU'),
  ('DEU010', 'SC Herford', 'DEU'),
  ('DEU011', 'Eintracht Braunschweig', 'DEU'),
  ('DEU012', 'Rot-Weiss Ahlen', 'DEU'),
  ('DEU013', 'FSV Union Fürstenwalde', 'DEU'),
  ('DEU014', 'MSV Duisburg', 'DEU'),
  ('DEU015', 'SV Waldhof Mannheim', 'DEU'),
  ('DEU016', 'HSV Barmbek-Uhlenhorst', 'DEU'),
  ('DEU017', 'TSG Sprockhövel', 'DEU'),
  ('DEU018', 'VfB Oldenburg', 'DEU'),
  ('DEU019', 'SC Paderborn 07', 'DEU'),
  ('DEU020', 'FC Memmingen', 'DEU'),
  ('DEU021', 'Chemnitzer FC', 'DEU'),
  ('DEU022', 'TSV 1860 Rosenheim', 'DEU'),
  ('DEU023', '1. FC Zeitz', 'DEU'),
  ('DEU024', 'Schwarz-Weiß Essen', 'DEU'),
  ('DEU025', 'FSV Zwickau', 'DEU'),
  ('DEU026', 'SV Schalding-Heining', 'DEU'),
  ('DEU027', 'TSV Bogen', 'DEU'),
  ('DEU028', 'Lokomotive Stendal', 'DEU'),
  ('DEU029', 'SV Babelsberg 03', 'DEU'),
  ('DEU030', 'SC Eltersdorf', 'DEU'),
  ('DEU031', 'Bayer 04 Leverkusen', 'DEU'),
  ('DEU032', 'ZFC Meuselwitz', 'DEU'),
  ('DEU033', 'Rot-Weiss Essen', 'DEU'),
  ('DEU034', '1. FC Lokomotive Leipzig', 'DEU'),
  ('DEU035', '1. FC Pforzheim', 'DEU'),
  ('DEU036', 'Kickers Offenbach', 'DEU'),
  ('DEU037', 'TSG Neustrelitz', 'DEU'),
  ('DEU038', 'Tennis Borussia Berlin', 'DEU'),
  ('DEU039', 'DSC Wanne-Eickel', 'DEU'),
  ('DEU040', 'F.C. Hansa Rostock', 'DEU'),
  ('DEU041', 'FC Oberlausitz Neugersdorf', 'DEU'),
  ('DEU042', 'FC Amberg', 'DEU'),
  ('DEU043', 'Berliner FC Dynamo', 'DEU'),
  ('DEU044', 'BCF Wolfratshausen', 'DEU'),
  ('DEU045', 'SpVgg Ansbach', 'DEU'),
  ('DEU046', 'SpVgg Bayern Hof', 'DEU'),
  ('DEU047', 'Hertha BSC', 'DEU'),
  ('DEU048', 'FC Viktoria Köln 1904', 'DEU'),
  ('DEU049', 'SCC Berlin', 'DEU'),
  ('DEU050', 'SV Merseburg', 'DEU'),
  ('DEU051', '1. SC Feucht', 'DEU'),
  ('DEU052', 'SV Drochtersen/Assel', 'DEU'),
  ('DEU053', 'FSV Wacker 90 Nordhausen', 'DEU'),
  ('DEU054', 'FC Ismaning', 'DEU'),
  ('DEU055', 'FC Astoria Walldorf', 'DEU'),
  ('DEU056', 'SV Heimstetten', 'DEU'),
  ('DEU057', 'TuS Koblenz', 'DEU'),
  ('DEU058', 'Hannover 96', 'DEU'),
  ('DEU059', 'Würzburger Kickers', 'DEU'),
  ('DEU060', 'FC Heilbronn', 'DEU'),
  ('DEU061', '1. FC Kleve', 'DEU'),
  ('DEU062', 'Viktoria Aschaffenburg', 'DEU'),
  ('DEU063', 'SC Freiburg', 'DEU'),
  ('DEU064', 'Karlsruher SC', 'DEU'),
  ('DEU065', 'SV Erlenbach', 'DEU'),
  ('DEU066', '1. FC Kaiserslautern', 'DEU'),
  ('DEU067', 'FSV Mainz 05', 'DEU'),
  ('DEU068', 'SV Motor Altenburg', 'DEU'),
  ('DEU069', 'SSV Reutlingen', 'DEU'),
  ('DEU070', 'FC Bayern Alzenau', 'DEU'),
  ('DEU071', 'TSV Buchbach', 'DEU'),
  ('DEU072', 'VfL Wolfsburg', 'DEU'),
  ('DEU073', 'BV Cloppenburg', 'DEU'),
  ('DEU074', '1. FC Sand', 'DEU'),
  ('DEU075', 'TSV Großbardorf', 'DEU'),
  ('DEU076', 'ETSV Weiche', 'DEU'),
  ('DEU077', 'SpVgg Hankofen-Hailing', 'DEU'),
  ('DEU078', 'FC Pommern Stralsund', 'DEU'),
  ('DEU079', 'Lüneburger SK Hansa', 'DEU'),
  ('DEU080', 'VfV 06 Hildesheim', 'DEU'),
  ('DEU081', 'Carl Zeiss Jena', 'DEU'),
  ('DEU082', 'SV Stahl Thale', 'DEU'),
  ('DEU083', 'SV Darmstadt 98', 'DEU'),
  ('DEU084', 'Eintracht Bad Kreuznach', 'DEU'),
  ('DEU085', '1. FC Neubrandenburg', 'DEU'),
  ('DEU086', 'Erzgebirge Aue', 'DEU'),
  ('DEU087', 'VfL Bochum', 'DEU'),
  ('DEU088', '1. FC Union Berlin', 'DEU'),
  ('DEU089', 'FC Oberneuland', 'DEU'),
  ('DEU090', '1. FC Bocholt', 'DEU'),
  ('DEU091', 'Eintracht Frankfurt', 'DEU'),
  ('DEU092', 'Fortuna Düsseldorf', 'DEU'),
  ('DEU093', 'BSG Chemie Leipzig', 'DEU'),
  ('DEU094', 'FC Schalke 04', 'DEU'),
  ('DEU095', 'Freiburger FC', 'DEU'),
  ('DEU096', '1. FC Germania Egestorf/Langreder', 'DEU'),
  ('DEU097', 'Türkiyemspor Berlin', 'DEU'),
  ('DEU098', 'SpVgg Erkenschwick', 'DEU'),
  ('DEU099', '1. FC Sonthofen', 'DEU'),
  ('DEU100', 'TSV Stahl Riesa', 'DEU'),
  ('DEU101', 'Teutonia Watzenborn-Steinberg', 'DEU'),
  ('DEU102', 'Chemie Böhlen', 'DEU'),
  ('DEU103', 'VfB Eppingen', 'DEU'),
  ('DEU104', 'DJK Vilzing', 'DEU'),
  ('DEU105', 'Berliner AK 07', 'DEU'),
  ('DEU106', 'SpVgg Unterhaching', 'DEU'),
  ('DEU107', 'FC Schweinfurt 05', 'DEU'),
  ('DEU108', 'Wuppertaler SV', 'DEU'),
  ('DEU109', 'SV Werder Bremen', 'DEU'),
  ('DEU110', 'SV Wilhelmshaven', 'DEU'),
  ('DEU111', 'VfR Mannheim', 'DEU'),
  ('DEU112', '1. FC Köln', 'DEU'),
  ('DEU113', '1. FC Magdeburg', 'DEU'),
  ('DEU114', 'BSV Schwarz-Weiß Rehden', 'DEU'),
  ('DEU115', 'BFC Alemannia 90 Wacker', 'DEU'),
  ('DEU116', 'Dresdner SC', 'DEU'),
  ('DEU117', '1. FC Mülheim', 'DEU'),
  ('DEU118', 'TSV Schwabmünchen', 'DEU'),
  ('DEU119', 'Eisenhüttenstädter FC Stahl', 'DEU'),
  ('DEU120', '1. FC Heidenheim', 'DEU'),
  ('DEU121', 'Stuttgarter Kickers', 'DEU'),
  ('DEU122', 'TSV Kottern', 'DEU'),
  ('DEU123', 'FSV Glückauf Brieske-Senftenberg', 'DEU'),
  ('DEU124', 'SV Seligenporten', 'DEU'),
  ('DEU125', 'SG Wattenscheid 09', 'DEU'),
  ('DEU126', '1. FC Saarbrücken', 'DEU'),
  ('DEU127', 'Sportfreunde Siegen', 'DEU'),
  ('DEU128', 'Borussia Neunkirchen', 'DEU'),
  ('DEU129', 'FC Gundelfingen', 'DEU'),
  ('DEU130', 'FSV 63 Luckenwalde', 'DEU'),
  ('DEU131', 'FC Hanau 93', 'DEU'),
  ('DEU132', 'FC Schönberg 95', 'DEU'),
  ('DEU133', 'SG Sonnenhof Großaspach', 'DEU'),
  ('DEU134', 'FV Illertissen', 'DEU'),
  ('DEU135', 'Meeraner SV', 'DEU'),
  ('DEU136', 'Preußen Münster', 'DEU'),
  ('DEU137', 'FC Bayern Munich', 'DEU'),
  ('DEU138', 'SV Kirchanschöring', 'DEU'),
  ('DEU139', 'FSV Budissa Bautzen', 'DEU'),
  ('DEU140', 'Hallescher FC', 'DEU'),
  ('DEU141', 'FC St. Pauli', 'DEU'),
  ('DEU142', 'Fortuna Babelsberg', 'DEU'),
  ('DEU143', 'VfL Osnabrück', 'DEU'),
  ('DEU144', 'VfB Auerbach', 'DEU'),
  ('DEU145', 'FC Remscheid', 'DEU'),
  ('DEU146', 'Dynamo Dresden', 'DEU'),
  ('DEU147', 'Holstein Kiel', 'DEU'),
  ('DEU148', 'FC 08 Homburg', 'DEU'),
  ('DEU149', 'FC Eintracht Norderstedt 03', 'DEU'),
  ('DEU150', 'VfR Garching', 'DEU'),
  ('DEU151', 'SC 1903 Weimar', 'DEU'),
  ('DEU152', 'TSV Havelse', 'DEU'),
  ('DEU153', 'SpVgg Bayreuth', 'DEU'),
  ('DEU154', 'FC Rot-Weiß Erfurt', 'DEU'),
  ('DEU155', 'Blau-Weiß Berlin', 'DEU'),
  ('DEU156', 'Fortuna Köln', 'DEU'),
  ('DEU157', 'FC Altona 93', 'DEU'),
  ('DEU158', 'OSC Bremerhaven', 'DEU'),
  ('DEU159', 'KSV Baunatal', 'DEU'),
  ('DEU160', 'RB Leipzig', 'DEU'),
  ('DEU161', 'FC Ingolstadt 04', 'DEU'),
  ('DEU162', '1. FC Weißenfels', 'DEU'),
  ('DEU163', 'FSV Oggersheim', 'DEU'),
  ('DEU164', 'SV Lichtenberg 47', 'DEU'),
  ('DEU165', 'Borussia Mönchengladbach', 'DEU'),
  ('DEU166', 'Goslarer SC 08', 'DEU'),
  ('DEU167', 'VfR Aalen', 'DEU'),
  ('DEU168', 'VfB Eichstätt', 'DEU'),
  ('DEU169', 'SV Wacker Burghausen', 'DEU'),
  ('DEU170', 'SSV Jahn Regensburg', 'DEU'),
  ('DEU171', 'Energie Cottbus', 'DEU'),
  ('DEU172', 'TSV Steinbach', 'DEU'),
  ('DEU173', 'KFC Uerdingen 05', 'DEU'),
  ('DEU174', 'VfR Bürstadt', 'DEU'),
  ('DEU175', 'TSG 1899 Hoffenheim', 'DEU'),
  ('DEU176', 'Rot-Weiß Oberhausen', 'DEU'),
  ('DEU177', 'FC Mecklenburg Schwerin', 'DEU'),
  ('DEU178', 'Berliner SV', 'DEU'),
  ('DEU179', 'Bonner SC', 'DEU'),
  ('DEU180', 'SV Meppen', 'DEU'),
  ('DEU181', '1. FC Union Solingen', 'DEU'),
  ('DEU182', 'TSR Olympia Wilhelmshaven', 'DEU'),
  ('DEU183', 'Wormatia Worms', 'DEU'),
  ('DEU184', 'FC Stahl Brandenburg', 'DEU'),
  ('DEU185', 'Göttingen 05', 'DEU'),
  ('DEU186', 'FC Nöttingen', 'DEU'),
  ('DEU187', 'BSV 07 Schwenningen', 'DEU'),
  ('DEU188', 'SV Elversberg', 'DEU'),
  ('DEU189', '1. FC Frankfurt', 'DEU'),
  ('DEU190', 'TSV 1865 Dachau', 'DEU'),
  ('DEU191', 'VFC Plauen', 'DEU'),
  ('DEU192', 'DJK Ammerthal', 'DEU'),
  ('DEU193', 'SV Wehen Wiesbaden', 'DEU'),
  ('DEU194', 'Alemannia Aachen', 'DEU'),
  ('DEU195', 'SSV Ulm 1846', 'DEU'),
  ('DEU196', 'FC Anker Wismar', 'DEU'),
  ('DEU197', 'SpVgg Weiden', 'DEU'),
  ('DEU198', '1. FC Nuremberg', 'DEU'),
  ('DEU199', 'FC Unterföhring', 'DEU'),
  ('DEU200', 'BSG Wismut Gera', 'DEU'),
  ('DEU201', 'FSV Salmrohr', 'DEU'),
  ('DEU202', 'KSV Hessen Kassel', 'DEU'),
  ('DEU203', 'DJK Don Bosco Bamberg', 'DEU'),
  ('DEU204', 'Alemannia Haibach', 'DEU'),
  ('DEU205', 'FC Viktoria 1889 Berlin', 'DEU'),
  ('DEU206', 'Kickers Emden', 'DEU'),
  ('DEU207', 'Eintracht Bamberg', 'DEU'),
  ('DEU208', 'SC Pfullendorf', 'DEU'),
  ('DEU209', 'VfL Frohnlach', 'DEU'),
  ('DEU210', 'FC Gütersloh 2000', 'DEU'),
  ('DEU211', 'Bischofswerdaer FV 08', 'DEU'),
  ('DEU212', 'FK Pirmasens', 'DEU'),
  ('DEU213', '1. Suhler SV', 'DEU'),
  ('DEU214', 'SpVgg Greuther Fürth', 'DEU'),
  ('DEU215', 'OSV Hannover', 'DEU'),
  ('DEU216', 'SC Westfalia Herne', 'DEU'),
  ('DEU217', 'Lupo Martini Wolfsburg', 'DEU'),
  ('DEU218', 'SV Rödinghausen', 'DEU'),
  ('DEU219', 'VfB Stuttgart', 'DEU'),
  ('DEU220', 'SC Tasmania 1900 Berlin', 'DEU'),
  ('DEU221', 'Eintracht Trier', 'DEU'),
  ('DEU222', 'FC Pipinsried', 'DEU'),
  ('DEU223', 'SC Wiedenbrück 2000', 'DEU'),
  ('DEU224', 'FC Augsburg', 'DEU'),
  ('DEU225', 'SV Eichede', 'DEU'),
  ('DEU226', 'TSV 1860 München', 'DEU'),
  ('DEU227', 'SV Sandhausen', 'DEU'),
  ('DEU228', 'Borussia Dortmund', 'DEU'),
  ('DEU229', 'SV Pullach', 'DEU'),
  ('DEU230', 'Hamburger SV', 'DEU'),
  ('DEU231', 'Spandauer SV', 'DEU'),
  ('DEU232', 'FSV Frankfurt', 'DEU'),
  ('DEU233', 'Sportfreunde Lotte', 'DEU'),
  ('DEU234', 'SC Verl', 'DEU'),
  ('DEU235', 'Arminia Bielefeld', 'DEU'),
  ('DEU236', 'TSV Aubstadt', 'DEU'),
  ('DEU237', 'Karlsruher FV', 'DEU');
