INSERT INTO Team (teamCode, teamName, teamCountryCode) VALUES
  ('FRA001', 'Brest', 'FRA'),
  ('FRA002', 'FC Girondins de Bordeaux', 'FRA'),
  ('FRA003', 'Angers SCO', 'FRA'),
  ('FRA004', 'Red Star', 'FRA'),
  ('FRA005', 'Olympique de Marseille', 'FRA'),
  ('FRA006', 'Le Havre', 'FRA'),
  ('FRA007', 'OSC Lille', 'FRA'),
  ('FRA008', 'AS Nancy', 'FRA'),
  ('FRA009', 'Valenciennes', 'FRA'),
  ('FRA010', 'Niort', 'FRA'),
  ('FRA011', 'Bourg-en-Bresse', 'FRA'),
  ('FRA012', 'AS Monaco FC', 'FRA'),
  ('FRA013', 'OGC Nice', 'FRA'),
  ('FRA014', 'FC Metz', 'FRA'),
  ('FRA015', 'Nimes', 'FRA'),
  ('FRA016', 'Orleans', 'FRA'),
  ('FRA017', 'Paris Saint-Germain', 'FRA'),
  ('FRA018', 'Ajaccio', 'FRA'),
  ('FRA019', 'Auxerre', 'FRA'),
  ('FRA020', 'FC Nantes', 'FRA'),
  ('FRA021', 'Clermont Foot', 'FRA'),
  ('FRA022', 'EA Guingamp', 'FRA'),
  ('FRA023', 'Troyes', 'FRA'),
  ('FRA024', 'Olympique Lyonnais', 'FRA'),
  ('FRA025', 'Tours', 'FRA'),
  ('FRA026', 'Toulouse FC', 'FRA'),
  ('FRA027', 'FC Lorient', 'FRA'),
  ('FRA028', 'Dijon FCO', 'FRA'),
  ('FRA029', 'Reims', 'FRA'),
  ('FRA030', 'Montpellier Hérault SC', 'FRA'),
  ('FRA031', 'Laval', 'FRA'),
  ('FRA032', 'Strasbourg', 'FRA'),
  ('FRA033', 'Stade Rennais FC', 'FRA'),
  ('FRA034', 'Amiens', 'FRA'),
  ('FRA035', 'Sochaux', 'FRA'),
  ('FRA036', 'SC Bastia', 'FRA'),
  ('FRA037', 'SM Caen', 'FRA'),
  ('FRA038', 'Lens', 'FRA'),
  ('FRA039', 'AS Saint-Étienne', 'FRA'),
  ('FRA040', 'Gazelec Ajaccio', 'FRA'),
  ('FRA041', 'Evian', 'FRA');
